set_party_mode:
  fields:
    mode:
      required: true
      example: halloween
      selector:
        select:
          options:
            - normal
            - halloween
            - christmas
            - easter
            - birthday
    device_id:
      required: false
      selector:
        device:
          integration: doorbell

set_house_state:
  fields:
    state:
      required: true
      example: away
      selector:
        select:
          options:
            - home
            - away
            - vacation
    device_id:
      required: false
      selector:
        device:
          integration: doorbell

purge_mqtt_discovery:
  fields:
    device_id:
      required: false
      selector:
        device:
          integration: doorbell
